# Generated by Django 5.2 on 2025-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('interest', models.CharField(choices=[('accounting', 'Accounting'), ('business', 'Business Management'), ('technology', 'Information Technology'), ('education', 'Education'), ('journalism', 'Journalism'), ('political_science', 'Political Science'), ('public_admin', 'Public Administration'), ('criminology', 'Criminology'), ('secretarial', 'Secretarial Studies')], max_length=20)),
                ('course', models.CharField(blank=True, choices=[('bsa', 'Bachelor of Science in Accountancy'), ('bsba', 'Bachelor of Science in Business Administration'), ('bsma', 'Bachelor of Science in Management Accountancy'), ('bsit', 'Bachelor of Science in Information Technology'), ('bs_crim', 'Bachelor of Science in Criminology'), ('ab_journ', 'Bachelor of Arts in Journalism'), ('ab_pol_sci', 'Bachelor of Arts in Political Science'), ('bpa', 'Bachelor of Public Administration'), ('beed_early', 'Bachelor in Elementary Education - Early Childhood Education'), ('beed_eng', 'Bachelor in Elementary Education - English'), ('beed_math', 'Bachelor in Elementary Education - Mathematics'), ('bsed_eng', 'Bachelor in Secondary Education - English'), ('bsed_ss', 'Bachelor in Secondary Education - Social Studies'), ('acs', 'Associate in Computer Secretarial')], max_length=20, null=True)),
            ],
        ),
    ]
