# Generated by Django 5.2 on 2025-05-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='course',
            field=models.CharField(blank=True, choices=[('accountancy', 'Accountancy'), ('bsit', 'BSIT'), ('criminology', 'Criminology'), ('education', 'Education'), ('financial_mgmt', 'Financial Management'), ('hrm', 'Human Resource Management'), ('polsci', 'Political Science'), ('social_work', 'Social Work')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='interest',
            field=models.CharField(choices=[('accounting', 'Accounting'), ('bookkeeping', 'Bookkeeping'), ('business', 'Business'), ('child education', 'Child Education'), ('coding', 'Coding'), ('community service', 'Community Service'), ('conflict resolution', 'Conflict Resolution'), ('cybersecurity', 'Cybersecurity'), ('data science', 'Data Science'), ('debate', 'Debate'), ('finance', 'Finance'), ('forensics', 'Forensics'), ('gaming', 'Gaming'), ('history', 'History'), ('investigation', 'Investigation'), ('investment', 'Investment'), ('law enforcement', 'Law Enforcement'), ('lesson planning', 'Lesson Planning'), ('networking', 'Networking'), ('numbers', 'Numbers'), ('philosophy', 'Philosophy'), ('politics', 'Politics'), ('psychology', 'Psychology'), ('public speaking', 'Public Speaking'), ('recruitment', 'Recruitment'), ('social issues', 'Social Issues'), ('teaching', 'Teaching'), ('tech', 'Tech'), ('training', 'Training'), ('volunteering', 'Volunteering')], max_length=50),
        ),
    ]
