# Generated by Django 5.2 on 2025-05-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentinfo_course_alter_studentinfo_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='course',
            field=models.CharField(blank=True, choices=[('accountancy', 'Accountancy'), ('BSIT', 'BSIT'), ('criminology', 'Criminology'), ('education', 'Education'), ('financial_mgmt', 'Financial Management'), ('hrm', 'Human Resource Management'), ('polsci', 'Political Science'), ('social_work', 'Social Work')], max_length=50, null=True),
        ),
    ]
